# Generated by Django 5.2.1 on 2025-06-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='semester_name',
        ),
    ]
