# Generated by Django 5.2.1 on 2025-06-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=100, null=True),
        ),
    ]
