# Generated by Django 5.2.1 on 2025-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_format',
            field=models.CharField(blank=True, help_text='MIME type of the uploaded file (e.g., application/pdf)', max_length=100, null=True),
        ),
    ]
