from .degree_level import DegreeLevel
from .program import Program
from .academic_year import AcademicYear
from .semester import Semester
from .course import Course
from .user import User
from .document import Document
from .points_history import PointsHistory
from .upload_log import UploadLog