# Generated by Django 5.2.1 on 2025-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Archivus', max_length=255)),
                ('about_text', models.TextField(default='Welcome to Archivus! Our project is dedicated to providing seamless digital archiving solutions for everyone at DAU.')),
                ('mission_title', models.CharField(default='Our Mission', max_length=255)),
                ('mission_text', models.TextField(default='Since DAU is a few-years program, time is limited. We wanted to create a common portal for all current and future students—a site that serves as a comprehensive paper vault for easy access to important resources.')),
                ('logo', models.ImageField(blank=True, help_text='Optional: A logo to display on the About Us page. If empty, a placeholder will be used.', null=True, upload_to='about_us_assets/')),
            ],
            options={
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text="Upload team member's photo.", null=True, upload_to='team_members/')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
    ]
